name = "Pfaffian"
uuid = "7b6dc561-4aaf-4161-978b-969903899dfe"
authors = ["RuQing Xu <r-xu@g.ecc.u-tokyo.ac.jp>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
UnsafeArrays = "c4a57d5a-5b31-53a6-b365-19f8c011fbd6"
